[package]
name = "recursive_variadic"
version = "0.1.0"
authors = ["rphmeier <rphmeier@gmail.com>"]
license = "MIT"
description = "type map at the type level"
repository = "https://github.com/rphmeier/recursive_variadic"